import datetime

DAYS = ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')
MONTHS = ('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL/JEFF MONTH', 'MAY/ANGIE MONTH', 'JUNE/MADY MONTH', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER')

